# Generated by Django 2.2.4 on 2019-08-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20190831_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetU',
        ),
        migrations.AlterField(
            model_name='pet',
            name='available',
            field=models.BooleanField(),
        ),
    ]
